config/routes.rb
Rails.application.routes.draw do
  get 'info/index'

  get 'about/index'
  devise_for :users
  resources :logs
  resources :profile
  root 'profile#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :description, presence: true
  validate :ocurred_on_is_valid?

  private

  def ocurred_on_is_valid?
    if read_attribute(:ocurred_on).blank?
      self.errors.add(:ocurred_on, "can't be blank.")
    end

    begin
      Date.parse(read_attribute(:ocurred_on).to_s)
    rescue ArgumentError
      self.errors.add(:ocurred_on, "is not a valid date.")
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :logs
  

  def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(self.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception

end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def index
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :authenticate_user!

  def index
    logs
  end

  def show
    @user = logs.find(params[:id])
  end

  def create
    if new_log(log_params).save
      render json: {
        log: new_log.as_json
      }
    else
      render json: {
        errors: new_log.errors
      }
    end
  end

  def update
    if log.update(log_params)
      render json: {
        log: log.as_json
      }
    else
      render json: {
        errors: log.errors
      }
    end
  end

  def destroy
    log.destroy
    render json:{
      id: log.id
    }, status: :ok
  end

  private

  def log_params
    params.require(:log).permit(:name, :description, :ocurred_on)
  end

  def new_log(attrs={})
    @log ||= current_user.logs.build(attrs)
  end

  def log
    @log ||= current_user.logs.find(params[:id])
  end

  def logs
    @logs ||= current_user.logs
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
    @user = current_user
    @last_log = Log.last.created_at
  end
  def show
    @user = User.find(params[:id])
    @last_log = Log.last.created_at
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<div class="jumbotron text-center">
  <div class="container">
    <h1>About Climber's Log!</h1>
    <p> Climber's Log is an app for recording your training sessions.  The goal is to help you stay organized and train
      more efficiently.  You can record your session with a title, description, and a date.  I recommend making the title
      "Power", "Endurance", or "Strength".  The reasons for this are listed in the Training/Nutrition tab.
      Hope this helps!  If you would like to contact me regarding the app or to contribute please email me
      at JoeyR84@gmail.com.  Happy Training!
    </p>
  </div>
</div>

app/views/info/index.html.erb
<div class="container">
  <h1 class="page-header">Training<h1>
    <hr>
<iframe width="560" height="315" src="https://www.youtube.com/embed/FEt35BKm2OI" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
  <h1 class="page-header">Nutrition<h1>
    <hr>
<iframe width="560" height="315" src="https://www.youtube.com/embed/ncDFDz9k35o" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <% if key.eql? :notice %>
    <div class="alert alert-success" role="alert"><%= value %></div>
  <% elsif key.eql? :error %>
    <div class="alert alert-danger" role="alert"><%= value %></div>
  <% elsif key.eql? :warning %>
    <div class="alert alert-warning" role="alert"><%= value %></div>
  <% else %>
    <div class="alert alert-info" role="alert"><%= simple_format(value) %></div>
  <% end %>
<% end %>

app/views/layouts/_login_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid nav-top">
    <div class="navbar-header">
      <h2>Climber's Log</h2>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to current_user.email, edit_user_password_path(current_user)%></li>
          <li><%= link_to('Logout', destroy_user_session_path, method: :delete)%>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="nav-side-menu nav-side">
          <ul class="nav nav-tabs nav-stacked list-group">
            <li class="list-group-item">
              <%= link_to (raw("<h3>Profile</h3>")), profile_path(current_user) %>
            </li>
            <li class="list-group-item">
              <%= link_to (raw("<h3>Logs</h3>")), logs_path(@logs) %>
            </li>
            <li class="list-group-item">
              <%= link_to (raw("<h3>About</h3>")), about_index_path() %>
            </li>
            <li class="list-group-item">
              <%= link_to (raw("<h3>Training/Nutrition</h3>")), info_index_path() %>
            </li>
          </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClimberLog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>
  <body>
    <div id="wrap">
      <% if !current_user %>

        <div class="container logout-container">
          <div class="row">
            <div class="col-sm-12 main">
              <%= render "layouts/flashes"  %>
              <%= yield %>
            </div>
          </div>
        </div>
      <% else %>
        <div class="container-fluid">
          <%= render 'layouts/login_nav' %>
        </div>
        <div class="main-container">
          <div class="row">
            <% if current_user %>
              <div class="col-sm-4 col-md-3 col-lg-3 sidebar_logged_in">
                <%=  render 'layouts/sidebar'%>
              </div>
              <div class="col-sm-8 col-md-9 col-lg-9 main_logged_in">
                <%= render "layouts/flashes"  %>
                <%= yield %>
              </div>
            <% else %>
              <div class="col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1 main">
                <%= render "layouts/flashes"  %>
                <%= yield %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </body>
</html>

app/views/logs/index.html.erb
<div id="log-background">
  <%= react_component('logs/index', logs: @logs, authenticity_token: form_authenticity_token) %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/show.html.erb
<h1>Welcome#show</h1>
<p>Find me in app/views/welcome/show.html.erb</p>